name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Ou 'master', dependendo da sua configuração

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: |
          docker build . -t my-node-app

      - name: Push Docker image
        run: |
          docker tag my-node-app yofate/my-new-node-app:${{ github.sha }}  # Atualizado para o novo repositório
          docker push yofate/my-new-node-app:${{ github.sha }}  # Atualizado para o novo repositório
